--- 
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata: 
  labels: 
    k8s-app: fluentd-es
  name: fluentd-es-v1.22
  namespace: kube-system
spec: 
#  selector: 
#    k8s-app: fluentd-es
#    version: v1.22
  template: 
    metadata: 
      labels: 
        k8s-app: fluentd-es
        version: v1.22
    spec: 
      containers: 
        - 
          command: 
            - /bin/sh
            - "-c"
            - "/usr/sbin/td-agent 2>&1 >> /var/log/fluentd.log"
          image: "gcr.io/google_containers/fluentd-elasticsearch:1.22"
          imagePullPolicy: IfNotPresent
          name: fluentd-es
          resources: 
            limits: 
              memory: 200Mi
            requests: 
              cpu: 100m
              memory: 200Mi
          volumeMounts: 
            - 
              mountPath: /var/log
              name: varlog
            - 
              mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
      volumes: 
        - 
          hostPath: 
            path: /var/log
          name: varlog
        - 
          hostPath: 
            path: /var/lib/docker/containers
          name: varlibdockercontainers
